### ISSUE TITLE
Google Maps API Key

### ISSUE THREAD

**Issue by raw-bit** [JustusPu/bachelor-thesis#1]
Hi

Just wanted to let you know I had to regenerate the API key for Maps. This is my bad as I published it on Codepen.
Thanks

**Comment by JustusPu** [comment]
Hey,

I'm sorry. I had copy your code snippet for generating a google maps PlaneGeometry in my visualization and didn't change the api key until now. I will change it as soon as possible. 

A little tip to prevent future misunderstandings:
You can limit your Google API keys, so only CodePen has access. But I'm very grateful you didn't, so I was able to test it first how it works. Anyway, it was my fault, it wasn't permitted to use your API key in my GitHub repository. I am very sorry. 

However I wish you a pleasant day!
